"""add form tariq occasion to poems, poet_id stanza to verses

Revision ID: 5af5060ac048
Revises: 5e5ec39e409d
Create Date: 2026-04-15 12:34:01.358940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af5060ac048'
down_revision: Union[str, Sequence[str], None] = '5e5ec39e409d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poems', sa.Column('form', sa.String(length=64), nullable=False))
    op.add_column('poems', sa.Column('tariq', sa.String(length=128), nullable=True))
    op.add_column('poems', sa.Column('occasion', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_poems_form'), 'poems', ['form'], unique=False)
    op.add_column('verses', sa.Column('poet_id', sa.UUID(), nullable=True))
    op.add_column('verses', sa.Column('stanza_index', sa.Integer(), nullable=True))
    op.add_column('verses', sa.Column('stanza_role', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_verses_poet_id'), 'verses', ['poet_id'], unique=False)
    op.create_foreign_key(None, 'verses', 'poets', ['poet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verses', type_='foreignkey')
    op.drop_index(op.f('ix_verses_poet_id'), table_name='verses')
    op.drop_column('verses', 'stanza_role')
    op.drop_column('verses', 'stanza_index')
    op.drop_column('verses', 'poet_id')
    op.drop_index(op.f('ix_poems_form'), table_name='poems')
    op.drop_column('poems', 'occasion')
    op.drop_column('poems', 'tariq')
    op.drop_column('poems', 'form')
    # ### end Alembic commands ###
