"""initial schema

Revision ID: 5e5ec39e409d
Revises: 
Create Date: 2026-04-15 11:33:55.139280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e5ec39e409d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_ar', sa.String(length=256), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('kunya', sa.String(length=128), nullable=True),
    sa.Column('laqab', sa.String(length=128), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=64), nullable=False),
    sa.Column('tradition', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('tribe', sa.String(length=128), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('signature_meters', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('signature_themes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('diwan_url', sa.String(length=512), nullable=True),
    sa.Column('wikipedia_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poets_era'), 'poets', ['era'], unique=False)
    op.create_index(op.f('ix_poets_name_ar'), 'poets', ['name_ar'], unique=False)
    op.create_index(op.f('ix_poets_tradition'), 'poets', ['tradition'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('tradition_context', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('channel', sa.String(length=256), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('tradition', sa.String(length=64), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_event_type'), 'videos', ['event_type'], unique=False)
    op.create_index(op.f('ix_videos_platform_id'), 'videos', ['platform_id'], unique=True)
    op.create_index(op.f('ix_videos_tradition'), 'videos', ['tradition'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls_json', sa.Text(), nullable=True),
    sa.Column('tool_results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('poems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('poet_id', sa.UUID(), nullable=True),
    sa.Column('poet_name', sa.String(length=256), nullable=True),
    sa.Column('tradition', sa.String(length=64), nullable=False),
    sa.Column('language_type', sa.String(length=64), nullable=False),
    sa.Column('meter', sa.String(length=64), nullable=False),
    sa.Column('meter_raw', sa.String(length=256), nullable=True),
    sa.Column('rhyme_letter', sa.String(length=8), nullable=True),
    sa.Column('rhyme_harakah', sa.String(length=32), nullable=True),
    sa.Column('sadr_rhyme', sa.String(length=8), nullable=True),
    sa.Column('ajuz_rhyme', sa.String(length=8), nullable=True),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('theme_raw', sa.String(length=256), nullable=True),
    sa.Column('era', sa.String(length=64), nullable=False),
    sa.Column('dialect', sa.String(length=64), nullable=True),
    sa.Column('verse_count', sa.Integer(), nullable=False),
    sa.Column('sources', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('canonical_source', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poet_id'], ['poets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poems_era'), 'poems', ['era'], unique=False)
    op.create_index(op.f('ix_poems_meter'), 'poems', ['meter'], unique=False)
    op.create_index(op.f('ix_poems_poet_id'), 'poems', ['poet_id'], unique=False)
    op.create_index(op.f('ix_poems_rhyme_letter'), 'poems', ['rhyme_letter'], unique=False)
    op.create_index(op.f('ix_poems_theme'), 'poems', ['theme'], unique=False)
    op.create_index(op.f('ix_poems_tradition'), 'poems', ['tradition'], unique=False)
    op.create_table('verses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poem_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_diacritized', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verses_poem_id'), 'verses', ['poem_id'], unique=False)
    op.create_table('video_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('speaker_id', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('identified_verse_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['identified_verse_id'], ['verses.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_segments_video_id'), 'video_segments', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_segments_video_id'), table_name='video_segments')
    op.drop_table('video_segments')
    op.drop_index(op.f('ix_verses_poem_id'), table_name='verses')
    op.drop_table('verses')
    op.drop_index(op.f('ix_poems_tradition'), table_name='poems')
    op.drop_index(op.f('ix_poems_theme'), table_name='poems')
    op.drop_index(op.f('ix_poems_rhyme_letter'), table_name='poems')
    op.drop_index(op.f('ix_poems_poet_id'), table_name='poems')
    op.drop_index(op.f('ix_poems_meter'), table_name='poems')
    op.drop_index(op.f('ix_poems_era'), table_name='poems')
    op.drop_table('poems')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_videos_tradition'), table_name='videos')
    op.drop_index(op.f('ix_videos_platform_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_event_type'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_poets_tradition'), table_name='poets')
    op.drop_index(op.f('ix_poets_name_ar'), table_name='poets')
    op.drop_index(op.f('ix_poets_era'), table_name='poets')
    op.drop_table('poets')
    # ### end Alembic commands ###
