"""qafiya classification columns and annotation tables

Revision ID: fbdf0df5cbfe
Revises: 5af5060ac048
Create Date: 2026-04-16 12:19:04.634431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdf0df5cbfe'
down_revision: Union[str, Sequence[str], None] = '5af5060ac048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifier_guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guideline', sa.Text(), nullable=False),
    sa.Column('example_poem_id', sa.UUID(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['example_poem_id'], ['poems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qafiya_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poem_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('correct_rawiy', sa.String(length=8), nullable=True),
    sa.Column('correct_radf', sa.String(length=4), nullable=True),
    sa.Column('correct_harakah', sa.String(length=32), nullable=True),
    sa.Column('correct_type', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qafiya_annotations_poem_id'), 'qafiya_annotations', ['poem_id'], unique=False)
    op.add_column('poems', sa.Column('qafiya_rawiy', sa.String(length=8), nullable=True))
    op.add_column('poems', sa.Column('qafiya_radf', sa.String(length=4), nullable=True))
    op.add_column('poems', sa.Column('qafiya_taassis', sa.Boolean(), nullable=True))
    op.add_column('poems', sa.Column('qafiya_wasl', sa.String(length=4), nullable=True))
    op.add_column('poems', sa.Column('qafiya_harakah', sa.String(length=32), nullable=True))
    op.add_column('poems', sa.Column('qafiya_type', sa.String(length=32), nullable=True))
    op.add_column('poems', sa.Column('qafiya_pattern', sa.String(length=32), nullable=True))
    op.add_column('poems', sa.Column('qafiya_confidence', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_poems_qafiya_confidence'), 'poems', ['qafiya_confidence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poems_qafiya_confidence'), table_name='poems')
    op.drop_column('poems', 'qafiya_confidence')
    op.drop_column('poems', 'qafiya_pattern')
    op.drop_column('poems', 'qafiya_type')
    op.drop_column('poems', 'qafiya_harakah')
    op.drop_column('poems', 'qafiya_wasl')
    op.drop_column('poems', 'qafiya_taassis')
    op.drop_column('poems', 'qafiya_radf')
    op.drop_column('poems', 'qafiya_rawiy')
    op.drop_index(op.f('ix_qafiya_annotations_poem_id'), table_name='qafiya_annotations')
    op.drop_table('qafiya_annotations')
    op.drop_table('classifier_guidelines')
    # ### end Alembic commands ###
