from dataclasses import dataclass
from typing import List, Optional, Dict, Any
from datetime import datetime
from .quality import QualityAssessment
from .prosody import ProsodyValidationResult


@dataclass
class LLMPoem:
    """Represents a candidate poem generated by an LLM"""
    
    # Core poem data
    verses: List[str]
    llm_provider: str
    model_name: str
    constraints: Optional[Dict[str, Any]] = None
    generation_timestamp: Optional[datetime] = None
    
    # Validation results
    prosody_validation: Optional[ProsodyValidationResult] = None
    quality: Optional[QualityAssessment] = None
    
    def __post_init__(self):
        if self.generation_timestamp is None:
            self.generation_timestamp = datetime.now()
    
    def validate_line_count(self) -> bool:
        """Validate that poem has correct number of lines (even number)"""
        return len(self.verses) % 2 == 0 and len(self.verses) > 0
    
    @property
    def bait_count(self) -> int:
        """Number of complete baits (pairs of verses)"""
        return len(self.verses) // 2
    
    def get_baits(self) -> List[tuple]:
        """Get poem as list of baits (verse pairs)"""
        if not self.validate_line_count():
            return []
        return [(self.verses[i], self.verses[i+1]) for i in range(0, len(self.verses), 2)]
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "verses": self.verses,
            "llm_provider": self.llm_provider,
            "model_name": self.model_name,
            "constraints": self.constraints,
            "generation_timestamp": self.generation_timestamp.isoformat() if self.generation_timestamp else None,
            "prosody_validation": self.prosody_validation.to_dict() if self.prosody_validation else None,
            "quality": self.quality.to_dict() if self.quality else None
        } 